FROM rust:1.76-alpine as builder
WORKDIR /app
COPY . .
RUN rustup target add x86_64-unknown-linux-musl 
RUN apk update && apk add --no-cache musl-dev 
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM alpine:latest 
WORKDIR /app
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/backend . 
# Copy any static assets or config files needed by the backend if any
CMD ["./backend"] 